name: HookahPlugin
version: '1.0.0'
main: org.trivait.hookahPlugin.HookahPlugin
api-version: '1.21'
authors: [ TRIVAIT ]
commands:
  hookah:
    description: HookahPlugin admin commands
    usage: /hookah <toggle|toggleEffects>
    permission: hookahplugin.admin
permissions:
  hookahplugin.admin:
    description: Access to /hookah commands
    default: op
